# Generated by Django 5.0.6 on 2024-06-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_taskcategory_tasks'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='categroy',
            field=models.ManyToManyField(to='category.taskcategory'),
        ),
    ]
