# Generated by Django 5.0.6 on 2024-06-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_categroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='categroy',
            new_name='category',
        ),
    ]
