# Generated by Django 5.0.6 on 2024-06-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='text_field',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='time_field',
            field=models.TimeField(default=None),
        ),
    ]
